server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        #git:
          #uri: https://github.com/damuls/spring-cloud-starter/     # 配置git仓库的地址
          #usearch-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          #uusername: yourname                                        # git仓库的账号
          #upassword: yourpass                                    # git仓库的密码
  rabbitmq:
    host: 192.168.0.6
    port: 5672
    username: admin
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址


management:
  security:
     enabled: false

